//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp.MAUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleApp.MAUI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - All packaging print/text must be readable in the image. It may be necessary to take multiple pictures of the fine print..
        /// </summary>
        internal static string NewItemTutorialAllPackagingInfo {
            get {
                return ResourceManager.GetString("NewItemTutorialAllPackagingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be asked to take pictures of the product from different angles as well as the fine print..
        /// </summary>
        internal static string NewItemTutorialAnglesInfo {
            get {
                return ResourceManager.GetString("NewItemTutorialAnglesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad.
        /// </summary>
        internal static string NewItemTutorialBad {
            get {
                return ResourceManager.GetString("NewItemTutorialBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Images Examples:.
        /// </summary>
        internal static string NewItemTutorialBadExamples {
            get {
                return ResourceManager.GetString("NewItemTutorialBadExamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Eliminate as much glare as possible..
        /// </summary>
        internal static string NewItemTutorialEliminateGlare {
            get {
                return ResourceManager.GetString("NewItemTutorialEliminateGlare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background is not clear/shows unnecessary items.
        /// </summary>
        internal static string NewItemTutorialFailImageBackgroundNotClear {
            get {
                return ResourceManager.GetString("NewItemTutorialFailImageBackgroundNotClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is blurry and bag is scrunched.
        /// </summary>
        internal static string NewItemTutorialFailImageBlurry {
            get {
                return ResourceManager.GetString("NewItemTutorialFailImageBlurry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand in photo.
        /// </summary>
        internal static string NewItemTutorialFailImageHandInPhoto {
            get {
                return ResourceManager.GetString("NewItemTutorialFailImageHandInPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients are blurry and unreadable.
        /// </summary>
        internal static string NewItemTutorialFailImageIngredientsBlurry {
            get {
                return ResourceManager.GetString("NewItemTutorialFailImageIngredientsBlurry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irrelevant photo.
        /// </summary>
        internal static string NewItemTutorialFailImageIreelevantPhoto {
            get {
                return ResourceManager.GetString("NewItemTutorialFailImageIreelevantPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is cut off/ make sure coupon is not covering text.
        /// </summary>
        internal static string NewItemTutorialFailImageIsCutOff {
            get {
                return ResourceManager.GetString("NewItemTutorialFailImageIsCutOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is distorted/can&apos;t tell size.
        /// </summary>
        internal static string NewItemTutorialFailImageIsDistorted {
            get {
                return ResourceManager.GetString("NewItemTutorialFailImageIsDistorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No UPC.
        /// </summary>
        internal static string NewItemTutorialFailImageNoUpc {
            get {
                return ResourceManager.GetString("NewItemTutorialFailImageNoUpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging is damaged.
        /// </summary>
        internal static string NewItemTutorialFailImagePackagingDamaged {
            get {
                return ResourceManager.GetString("NewItemTutorialFailImagePackagingDamaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All of product/text isn&apos;t shown/ must move flap to image all text.
        /// </summary>
        internal static string NewItemTutorialFailImageProductNotShown {
            get {
                return ResourceManager.GetString("NewItemTutorialFailImageProductNotShown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf/Price is also pictured.
        /// </summary>
        internal static string NewItemTutorialFailImageShelfPrice {
            get {
                return ResourceManager.GetString("NewItemTutorialFailImageShelfPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top tab is not pictured individually.
        /// </summary>
        internal static string NewItemTutorialFailImageTopNotPictured {
            get {
                return ResourceManager.GetString("NewItemTutorialFailImageTopNotPictured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnecessary product that did not appear on generation list.
        /// </summary>
        internal static string NewItemTutorialFailImageUnnecessaryProduct {
            get {
                return ResourceManager.GetString("NewItemTutorialFailImageUnnecessaryProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPC is covered by text.
        /// </summary>
        internal static string NewItemTutorialFailImageUpcCoveredByText {
            get {
                return ResourceManager.GetString("NewItemTutorialFailImageUpcCoveredByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPC is cut off.
        /// </summary>
        internal static string NewItemTutorialFailImageUpcCutOff {
            get {
                return ResourceManager.GetString("NewItemTutorialFailImageUpcCutOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPC isn&apos;t pictured correctly.
        /// </summary>
        internal static string NewItemTutorialFailImageUpcNotPictured {
            get {
                return ResourceManager.GetString("NewItemTutorialFailImageUpcNotPictured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glare on front/UPC unreadable.
        /// </summary>
        internal static string NewItemTutorialFailImageUpcUnreadable {
            get {
                return ResourceManager.GetString("NewItemTutorialFailImageUpcUnreadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Fill up as much of the screen with the product as possible for a minimal background..
        /// </summary>
        internal static string NewItemTutorialFillScreenInfo {
            get {
                return ResourceManager.GetString("NewItemTutorialFillScreenInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have completed the first step in submitting this product..
        /// </summary>
        internal static string NewItemTutorialFirstStepComplete {
            get {
                return ResourceManager.GetString("NewItemTutorialFirstStepComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        internal static string NewItemTutorialGood {
            get {
                return ResourceManager.GetString("NewItemTutorialGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Image Collection Guidelines:.
        /// </summary>
        internal static string NewItemTutorialGuidelineHeader {
            get {
                return ResourceManager.GetString("NewItemTutorialGuidelineHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Please avoid images containing human pictures..
        /// </summary>
        internal static string NewItemTutorialHumanPictures {
            get {
                return ResourceManager.GetString("NewItemTutorialHumanPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NewItemTutorialNext {
            get {
                return ResourceManager.GetString("NewItemTutorialNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: Please use sufficient light and capture each angle for the best product picture..
        /// </summary>
        internal static string NewItemTutorialNote {
            get {
                return ResourceManager.GetString("NewItemTutorialNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Take pictures of all packaging sides even if there isn&apos;t any wording or pictures..
        /// </summary>
        internal static string NewItemTutorialPackagingInfo {
            get {
                return ResourceManager.GetString("NewItemTutorialPackagingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please take atleast one image for the following angles: Front, Back, Top, Bottom, Left, Right.
        /// </summary>
        internal static string NewItemTutorialQueueInfo {
            get {
                return ResourceManager.GetString("NewItemTutorialQueueInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips for the best quality images:.
        /// </summary>
        internal static string NewItemTutorialTips {
            get {
                return ResourceManager.GetString("NewItemTutorialTips", resourceCulture);
            }
        }
    }
}
